### ISSUE TITLE
Remove Daily nerd link from Weekly news

### ISSUE THREAD

**Issue by patil-vinod** [frontend-rescue/keep-up-to-date#99]
http://vasilis.nl/dailynerd/
Website says - This site is no longer updated. Many links are probably outdated. Or broken.

**Comment by patil-vinod** [comment]
Closed? :-1:

**Comment by pazguille** [comment]
Yes, I'm going to build a new version in a few minutes. :)

**Comment by patil-vinod** [comment]
Cool, thanks! :)
